name: selam_app
description: A mental health therapy app.

# Prevent accidental publishing to pub.dev.
publish_to: 'none' 

# Versioning for the app.
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^13.0.1
  flutter_riverpod: ^2.4.9
  shared_preferences: ^2.2.2
  google_fonts: ^6.1.0
  http: ^1.1.0
  intl: ^0.19.0

  # State Management
  provider: ^6.0.5
  riverpod_annotation: ^2.3.3

  # Network
  dio: ^5.4.0
  retrofit: ^4.0.3

  # Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0

  # UI Components
  flutter_screenutil: ^5.9.0
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  flutter_svg: ^2.0.9

  # Utils
  logger: ^2.0.2+1
  json_annotation: ^4.8.1
  freezed_annotation: ^2.4.1

  # Video Playback
  video_player: ^2.8.2
  chewie: ^1.7.4

  # New dependencies
  dartz: ^0.10.1
  equatable: ^2.0.5
  timeago: ^3.6.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.13.1
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  freezed: ^2.4.6
  retrofit_generator: ^8.0.6
  hive_generator: ^2.0.1
  mockito: ^5.4.4
  integration_test:
    sdk: flutter
  riverpod_generator: ^2.3.9
  custom_lint: ^0.5.7
  riverpod_lint: ^2.3.4

flutter:
  # Enable code generation for localization
  generate: true

  # Include Material Icons
  uses-material-design: true

  # Asset directories
  assets:
    - assets/images/
    - assets/icons/
    - assets/videos/
    - lib/l10n/
    - .env

  # Uncomment and configure if you want to use custom fonts.
  # fonts:
  #   - family: Montserrat
  #     fonts:
  #       - asset: assets/fonts/Montserrat-Regular.ttf
  #       - asset: assets/fonts/Montserrat-Medium.ttf
  #         weight: 500
  #       - asset: assets/fonts/Montserrat-SemiBold.ttf
  #         weight: 600
  #       - asset: assets/fonts/Montserrat-Bold.ttf
  #         weight: 700

flutter_icons:
  android: true
  ios: true
  image_path: "assets/image/icon.png"
