// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIdzCdYy4Ko-d_NcR_o0vvfq8JJwYKxS0',
    appId: '1:124875569347:web:d1e4d9478e286d8b6bca76',
    messagingSenderId: '124875569347',
    projectId: 'selam-therapy-app-e6c45',
    authDomain: 'selam-therapy-app-e6c45.firebaseapp.com',
    storageBucket: 'selam-therapy-app-e6c45.firebasestorage.app',
    measurementId: 'G-JBL6NSLXX9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQOoOTAbdGA7HikW8wbz02A72B8pYYf2Y',
    appId: '1:124875569347:android:d85e3f0d09ee1fc56bca76',
    messagingSenderId: '124875569347',
    projectId: 'selam-therapy-app-e6c45',
    storageBucket: 'selam-therapy-app-e6c45.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCweTJXiRfb0Tt7UWgOAlRn3SyECHWrCK8',
    appId: '1:124875569347:ios:5b02abccb8f09d436bca76',
    messagingSenderId: '124875569347',
    projectId: 'selam-therapy-app-e6c45',
    storageBucket: 'selam-therapy-app-e6c45.firebasestorage.app',
    iosBundleId: 'com.example.selamApp',
  );
}
